language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install lxml -e .
  - pip install -U codecov pytest-cov

script:
  py.test --cov-report term --cov=cssselect

after_success:
  codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  user: redapple
  password:
    secure: T1PBD+ocIGwHMbBHPqzu7UZxpkB0w98KtEIkNzLXNQcF7JpjugZNwz4xX2xVhi8yvUQ257VtLSKpIOT2FWxrfLrgTZKbTd6Q7V5Lf3HKzLomOKUKMAd54gsOuismE27CT/SHbexskACgwVwkyG9Y3dlG6m/ZBgqoPAGaJrScjEU=
  on:
    tags: true
    repo: scrapy/cssselect
    condition: "$TRAVIS_PYTHON_VERSION == '3.6'"
