language: python
matrix:
  include:
    - python: 3.8
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=py27
    - python: pypy
      env: TOXENV=pypy
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: pypy3
      env: TOXENV=pypy3
install:
- pip install tox -r tests/requirements.txt -e .
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  user: scrapy
  password:
    secure: UjCXD1ZfqgFcCs4ciPMJDaOQefV3ZOKZ8/dTZxcoaQlE1lr6CkaN6CfTdD50SX2M9uCNWvEcYnvs6U4SizgZ27MYzFWuHonED2alHKy4AtrxCEHD/+lGo9d18cNjLMPDZateX/lITjGiZ4rmYZNuA6wmA4P/bTmdazbSufcmMqY=
  on:
    tags: true
    repo: scrapy/cssselect
    condition: "$TOXENV == py37"
